---
abstract: 'a family of templating and markup modules'
author:
  - 'Ben Deutsch <ben@bendeutsch.de>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Positron
requires:
  Carp: 0
  Data::Dump: 0
  File::Slurp: 0
  IO::String: 0
  JSON: 0
  Parse::RecDescent: 0
  Scalar::Util: 0
  Storable: 0
  perl: v5.10.0
resources:
  repository: git://github.com/bendeutsch/positron-template.git
version: v0.1.2
